import { readFile } from 'node:fs/promises';
import { schemaPath } from '../db.js';

function getTableName(createStatement) {
  const match = createStatement.match(
    /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(.+?)\s*\(/i,
  );
  return match?.[1]?.trim() ?? 'unknown_table';
}

function toPostgresSchemaText(text) {
  return text
    .replace(/`northwind`\.`([^`]+)`/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\bnorthwind\./g, '')
    .replace(/^default\s+/gim, '"default" ')
    .replace(/\bINT\(\d+\)/gi, 'INTEGER')
    .replace(/\bTINYINT\(\d+\)/gi, 'SMALLINT')
    .replace(/\bDOUBLE\b/gi, 'DOUBLE PRECISION')
    .replace(/\bDATETIME\b/gi, 'TIMESTAMP')
    .replace(/\bLONGTEXT\b/gi, 'TEXT')
    .replace(/\bLONGBLOB\b/gi, 'TEXT')
    .replace(/\bAUTO_INCREMENT\b/gi, 'GENERATED BY DEFAULT AS IDENTITY')
    .replace(/\s+DEFAULT\s+NULL/gi, '')
    .replace(/\s+ENGINE\s*=\s*InnoDB[\s\S]*?;/gi, ';');
}

export async function loadSchemaChunks() {
  const schema = await readFile(schemaPath, 'utf8');
  const chunks = [];
  const pattern = /((?:--[^\n]*\r?\n)+)\s*(CREATE\s+TABLE[\s\S]*?;)/gi;
  let match;

  while ((match = pattern.exec(schema)) !== null) {
    const commentBlock = match[1]
      .split(/\r?\n/)
      .map((line) => line.replace(/^--\s?/, '').trim())
      .filter(Boolean)
      .join('\n');
    const createTable = match[2].trim();
    const tableName = getTableName(createTable);

    chunks.push({
      key: tableName.replace(/`northwind`\.`([^`]+)`/, '$1').replaceAll('`', ''),
      text: toPostgresSchemaText(`${commentBlock}\n\n${createTable}`),
    });
  }

  return chunks;
}
